Monify/urls.py
from django.conf.urls import handler404
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('finances/', include('finances.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('change_currency/', views.change_currency, name='change_currency'),
    path('change_saving_method/', views.change_saving_method, name='change_saving_method'),
    path('profile/', views.profile, name='profile_info'),
    path('info/', views.info, name='info'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('delete_all_data/', views.delete_all_data, name='delete_all_data'),
    path('get_profile_data/', views.get_profile_data, name='get_profile_data'),
    path('password_reset/',
        auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html',
        email_template_name = 'accounts/password_reset_email.html',
        subject_template_name='accounts/password_reset_subject.txt',
        success_url = reverse_lazy('accounts:password_reset_done')),
        name='password_reset'),
    path('password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',
        success_url = reverse_lazy('accounts:password_reset_complete')),
        name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class Account(models.Model):
    CURRENCIES = [
        ('PLN', 'zł'),
        ('EUR', '€'),
        ('USD', '$'),
        ('NOK', 'Kr'),
        ('CHF', 'Fr'),
        ('GBP', '£'),
        ('JPY', '¥'),
        ('GBP', '£'),
        ('HRK', 'KN'),
        ('HUF', 'Ft'),
        ('CZK', 'Kč')
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    currency = models.CharField(max_length=6, null=True, choices=CURRENCIES, default=CURRENCIES[0][0])
    saving_method = models.CharField(max_length=30, null=True, choices=[('METODA 6 SŁOIKÓW', 'METODA 6 SŁOIKÓW'), ('METODA 50/30/20', 'METODA 50/30/20')], default='METODA 6 SŁOIKÓW')

    def __str__(self):
        return self.user.username

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

from .models import Account

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2']

    first_name = forms.Field(widget=forms.TextInput(attrs={
        'required': 'required'
    }))
    last_name = forms.Field(widget=forms.TextInput(attrs={
        'required': 'required'
    }))
    email = forms.Field(widget=forms.EmailInput(attrs={
        'required': 'required'
    }))
    password1 = forms.Field(widget=forms.PasswordInput(attrs={
        'required': 'required'
    }))
    password2 = forms.Field(widget=forms.PasswordInput(attrs={
        'required': 'required'
    }))

    def is_valid(self):
        is_valid = super().is_valid()

        if User.objects.filter(email=self.cleaned_data['email']).exists():
            self.add_error('email', 'Użytkownik o takim adresie email już istnieje.')
            is_valid = False

        return is_valid

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.username = instance.email
        if commit:
            instance.save()
        
        return instance

    def clean_password1(self):
        if not self.cleaned_data['password1']:
            raise forms.ValidationError("Enter a password.")
        return self.cleaned_data['password1']

    def clean_password2(self):
        if not self.cleaned_data['password2']:
            raise forms.ValidationError("Enter your password (again)")
        return self.cleaned_data['password2']

    def clean(self):
        cleaned_data = self.cleaned_data
        password1 = cleaned_data['password1']
        password2 = cleaned_data['password2']

        if len(password1) < 8:
            self.add_error('password1', 'Hasło musi zawierać co najmniej 8 znaków.')

        if password1.isdigit():
            self.add_error('password1', 'Hasło nie może się składać z samych cyfr.')

        # check for 2 digits
        if sum(p.isdigit() for p in password1) < 1:
            self.add_error('password1', 'Hasło musi zawierać co najmniej 1 cyfrę.')

        if not any(p.isupper() for p in password1):
            self.add_error('password1', 'Hasło musi zawierać co najmniej 1 dużą literę.')

        if password1 and password2:
            if password1 != password2:
                self.add_error('password1', 'Hasła nie są identyczne.')
        return cleaned_data

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

    def __init__(self, user, *args, **kwargs):
        super(CustomUserChangeForm, self).__init__(*args, **kwargs)
        current_user = User.objects.filter(pk = user.id).get()
        self.current_user_email = getattr(current_user, 'email')

    def is_valid(self):
        is_valid = super().is_valid()
        if self.current_user_email != self.cleaned_data['email']:
            if User.objects.filter(email=self.cleaned_data['email']).exists():
                self.add_error('email', 'Użytkownik o takim adresie email już istnieje.')
                is_valid = False

        return is_valid

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.username = instance.email
        if commit:
            instance.save()
        
        return instance

class ChangeUserCurrency(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['currency']

class ChangeUserSavingMethod(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['saving_method']
    

accounts/views.py
import json
from datetime import datetime
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import redirect, render

from finances.models import Balance, Income, Outcome
from .forms import CustomUserCreationForm, CustomUserChangeForm, ChangeUserCurrency, ChangeUserSavingMethod
from .models import Account

# registration function
def register(request):
    form = CustomUserCreationForm()
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data['email']
            user = User.objects.get(username=email)
            Balance.objects.create(value=0, date=datetime.today(), type=1, name="Karta", user=user)
            Balance.objects.create(value=0, date=datetime.today(), type=1, name="Gotówka", user=user)
            Account.objects.create(user=user, currency='PLN', saving_method='METODA 6 SŁOIKÓW', user_id=user.id)
            messages.success(request, f'Pomyślnie zarejestrowano użytkownika o adresie email: {email}.')
    context = {'form': form}

    return render(request, 'accounts/register.html', context)

# login function
def login_view(request):
    if request.user.is_authenticated:
        return redirect('finances:dashboard')
    username = ""
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        remember_me = request.POST.get('remember_me')
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            if not remember_me:
                request.session.set_expiry(0)
            return redirect('finances:dashboard')
        else:
            messages.warning(request, 'Podany login lub hasło są nieprawidłowe.')

    return render(request, 'accounts/login.html', context={'username': username})

# logout function
def logout_view(request):
    logout(request)
    messages.success(request, 'Wylogowano pomyślnie.')

    return redirect('accounts:login')

# This function allows user to change default currency
@login_required(login_url='accounts:login')
def change_currency(request):
    current_user_account = Account.objects.get(user_id=request.user.id)
    form = ChangeUserCurrency(request.POST or None, instance=current_user_account)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return HttpResponse(
                    status=204,
                    headers={
                        'HX-Trigger': json.dumps({
                            "profileDataChanged": None,
                        })
                    })
    context = {'form': form, 'header': 'currency'}

    return render(request, 'accounts/accounts_details_form.html', context)

# This function allows user to change default saving method
@login_required(login_url='accounts:login')
def change_saving_method(request):
    current_user_account = Account.objects.get(user_id=request.user.id)
    form = ChangeUserSavingMethod(request.POST or None, instance=current_user_account)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return HttpResponse(
                    status=204,
                    headers={
                        'HX-Trigger': json.dumps({
                            "profileDataChanged": None,
                        })
                    })
    context = {'form': form, 'header': 'saving_method'}

    return render(request, 'accounts/accounts_details_form.html', context)

# This function allows user to change profile data such as name, surname, etc.
@login_required(login_url='accounts:login')
def edit_profile(request):
    current_user = User.objects.get(id=request.user.id)
    user = request.user
    form = CustomUserChangeForm(user, request.POST or None, instance=current_user)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return HttpResponse(
                    status=204,
                    headers={
                        'HX-Trigger': json.dumps({
                            "profileDataChanged": None,
                        })
                    })
    context = {'form': form, 'header': 'edit_profile'}

    return render(request, 'accounts/edit_profile.html', context)

# This function allows user to clear all data (all balances, all icomes and all outcomes) at once
def delete_all_data(request):
    balances = Balance.objects.filter(user=request.user)
    incomes = Income.objects.filter(user=request.user)
    outcomes = Outcome.objects.filter(user=request.user)
    if request.method == "POST":
        balances.delete()
        incomes.delete()
        outcomes.delete()
        return HttpResponse(status=204)

    return render(request, 'finances/balance_income_outcome_confirm_delete.html', context={'model':'all_data'})

@login_required(login_url='accounts:login')
def get_profile_data(request):
    user_currency = Account.objects.get(user_id=request.user.id).get_currency_display()
    user_saving_method = Account.objects.get(user_id=request.user.id).get_saving_method_display()
    
    return render(request, 'accounts/get_profile_data.html', context={'user_currency': user_currency,'user_saving_method':user_saving_method})

@login_required(login_url='accounts:login')
def profile(request):
    return render(request, 'accounts/profile.html')

@login_required(login_url='accounts:login')
def info(request):
    return render(request, 'accounts/info.html')

templates/accounts/edit_profile_def.html
{% load widget_tweaks %}
{% with WIDGET_ERROR_CLASS='is-invalid' %}
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button>Zapisz</button>
</form>
{% endwith %}

templates/accounts/get_profile_data.html
<div>
  <div class="flex flex-col">
    <h1 class="text-5xl text-gray-700 mt-10 mx-auto">Profil</h1>
    <h1 class="text-8xl mt-10 mx-auto">
      <i class="font-bold fa-solid fa-circle-user text-gray-300"></i>
    </h1>
    <p class="text-3xl mt-4 mx-auto">
      {{ user.first_name }} {{ user.last_name }}
    </p>
    <p class="text-sm mt-2 mx-auto">{{ user.email }}</p>
    <div class="flex my-4">
      <button
        class="mx-auto text-base text-blue-500"
        @click="showModal = true"
        type="button"
        hx-get="{% url 'accounts:edit_profile' %}"
        hx-target="#dialog"
      >
        Zmień dane profilowe
      </button>
    </div>
  </div>
</div>
<div class="w-4/6 md:w-auto flex flex-row space-x-5 mx-auto">
  <div>
    <p class="text-lg md:text-xl md:mx-auto">
      Obecna metoda: <span class="font-bold">{{ user_saving_method }}</span>
    </p>
  </div>
  <div>
    <p class="text-lg border border-gray-400 rounded-xl hover:bg-gray-300">
      <button
        class="p-2 text-base"
        @click="showModal = true"
        type="button"
        hx-get="{% url 'accounts:change_saving_method' %}"
        hx-target="#dialog"
      >
        Zmień metodę
      </button>
    </p>
  </div>
</div>
<div class="flex flex-row space-x-5 mx-auto">
  <div>
    <p class="text-lg md:text-xl text-left">
      Waluta: <span class="font-bold">{{ user_currency }}</span>
    </p>
  </div>
  <div>
    <p class="text-lg border border-gray-400 rounded-xl hover:bg-gray-300">
      <button
        class="p-2 text-base"
        @click="showModal = true"
        type="button"
        hx-get="{% url 'accounts:change_currency' %}"
        hx-target="#dialog"
      >
        Zmień walutę
      </button>
    </p>
  </div>
</div>

templates/accounts/info.html
{% extends 'base.html' %}
{% block content %}

  <!-- Content -->
  <div class="container">
    <!-- Title -->
    <h1 class="text-4xl my-8 mx-10 text-gray-600">
      Informacje o metodach oszczędzania
    </h1>

    <!-- First method -->
    <div class="text-gray-600">
      <h1 class="text-3xl font-bold my-5 mx-10">Metoda 50/30/20</h1>
      <p class="text-lg mx-10">
        Metodę tą opracowała prof. Elizabeth Warren, która została wymieniona
        wśród 100 najbardziej wpływowych osób w USA na liście magazynu TIME.
        Metoda 50/30/20 jest jedną z najpopularniejszcyh metod oszczędzania
        pieniędzy. Metoda ta pozwala na wyrobienie właściwych nawyków finansowych
        oraz pozwala na łatwe kontrolowanie swoich wydatków.
      </p>
      <h2 class="text-2xl my-5 mx-10">Na czym polega metoda 50/30/20?</h2>
      <p class="text-lg mx-10">
        Metoda 50/30/20 polega na podziale naszych miesięcznych dochodów na 3
        części:
      </p>
      <ul class="text-lg md:ml-24 ml-16 md:mr-40 mr-10 list-disc">
        <li class="my-5">
          I - 50% przychodów - niezbędne wydatki - opłata za mieszkanie, spłata
          kredytów, rachunki, higiena, koszty leczenia i leki, kosmetyki, wydatki
          na szkołe i przedszkole, jedzenie i picie, transport, ubezpieczenie,
          samochód, parking i opłaty, karma dla zwierząt
        </li>
        <li class="my-5">
          II - 30% przychodów - przyjemności i rozrywka (zbędne wydatki) -
          restauracje, puby i bary, kluby, filmy, gry, muzyka, subskrypcje,
          elektronika, kino i teatr, wyjście ze znajomymi, wakacje, zabawa,
          koncert, rozrywka, dekoracje, meble, atrakcje/wypoczynek, zakupy
        </li>
        <li class="my-5">
          III - 20% przychodów - oszczędności i inwestycje - akcje, kryptowaluty,
          nieruchomości, dochód pasywny, fundusze, oszczędności, wpłata na lokate,
          inwestycja w surowce
        </li>
      </ul>
      <h2 class="text-2xl my-5 mx-10">Zalety metody 50/30/20</h2>
      <ul class="text-lg md:ml-20 ml-14 md:mr-40 mr-10">
        <li class="my-5">
          <span class="mr-3">👍</span> łatwa oraz nie restrykcyjna
        </li>
        <li class="my-5">
          <span class="mr-3">👍</span> główne założenie polega na unikaniu
          drobnych wydatków
        </li>
        <li class="my-5">
          <span class="mr-3">👍</span> uwzględnia wydatki na pasje oraz hobby
        </li>
        <li class="my-5">
          <span class="mr-3">👍</span> pozwala na efektywne oraz szybkie budowanie
          oszczędności
        </li>
      </ul>
      <h2 class="text-2xl my-5 mx-10">Wady metody 50/30/20</h2>
      <ul class="text-lg md:ml-20 ml-14 md:mr-40 mr-10">
        <li class="my-5">
          <span class="mr-3">👎</span> ciężko jednoznacznie określić co jest
          zbędne, a co niezbędne
        </li>
        <li class="my-5">
          <span class="mr-3">👎</span> nie jest przeznaczona dla wszystkich (np.
          czynsz może pochłaniać powyżej 50% naszych dochodów)
        </li>
      </ul>
    </div>

    <!-- Second method -->
    <div class="text-gray-600">
      <h1 class="text-3xl font-bold mt-10 mb-5 mx-10">Metoda 6 słoików</h1>
      <p class="text-lg mx-10">
        Metodę 6 słoików opracował T. Harv Eker, biznesmen, pisarz i mówca
        motywacyjny. Jest ona jedną z najpopularniejszcyh metod oszczędzania
        pieniędzy. Metoda polega na podziale miesięcznego dochodu na 6 części
        nazywanych "słoikami". W momencie, gdy dostajemy wypłatę dzielimy ją na 6
        części i odpowiednio umieszczamy w tytułowych "słoikach" lub na
        oddzielnych kontach bankowych, przeznaczonych do poszczególnych kategorii.
      </p>
      <h2 class="text-2xl my-5 mx-10">Na czym polega metoda 6 słoików?</h2>
      <p class="text-lg mx-10">
        Metoda 6 słoików polega na podziale naszych miesięcznych dochodów na 6
        części ("słoików"):
      </p>
      <ul class="text-lg md:ml-24 ml-16 md:mr-40 mr-10 list-disc">
        <li class="my-5">
          I słoik - 55% przychodów - niezbędne wydatki - opłata za mieszkanie,
          spłata kredytów, rachunki, higiena, koszty leczenia i leki, kosmetyki,
          wydatki na szkołe i przedszkole, jedzenie i picie, transport,
          ubezpieczenie, samochód, parking i opłaty, karma dla zwierząt
        </li>
        <li class="my-5">
          II słoik - 10% przychodów - duże/niespodziewane wydatki - duże zakupy,
          remont, wymiana sprzętów domowych, wakacje, niespodziewane wydatki(np.
          koszty lecznicze, naprawa samochodu), mandat, kary
        </li>
        <li class="my-5">
          III słoik - 10% przychodów - przyjemności i rozrywka - restauracje, puby
          i bary, kluby, filmy, gry, muzyka, subskrypcje, elektronika, kino i
          teatr, wyjście ze znajomymi, wakacje, zabawa, koncert, rozrywka,
          dekoracje, meble, atrakcje/wypoczynek, zakupy
        </li>
        <li class="my-5">
          IV słoik - 10% przychodów - edukacja - książki, kursy, szkolenia,
          mentoring
        </li>
        <li class="my-5">
          V słoik - 10% przychodów - oszczędności i inwestycje - spłata kredytów,
          akcje, kryptowaluty, nieruchomości, dochód pasywny, fundusze,
          oszczędności, wpłata na lokate, surowce, obligacje
        </li>
        <li class="my-5">
          VI słoik - 5% przychodów - pomoc innym/dobroczynność - datki na
          fundacje, pomoc potrzebującym, prezenty
        </li>
      </ul>
      <h2 class="text-2xl my-5 mx-10">Zalety metody 6 słoików</h2>
      <ul class="text-lg md:ml-20 ml-14 md:mr-40 mr-10">
        <li class="my-5">
          <span class="mr-3">👍</span> dobrze zbalansowany rozkład dochodów
        </li>
        <li class="my-5"><span class="mr-3">👍</span> bardzo efektywna</li>
        <li class="my-5"><span class="mr-3">👍</span> efektywna</li>
      </ul>
      <h2 class="text-2xl my-5 mx-10">Wady metody 6 słoików</h2>
      <ul class="text-lg md:ml-20 ml-14 md:mr-40 mr-10">
        <li class="my-5">
          <span class="mr-3">👎</span> bardziej restrykcyjna od metody 50/30/20
        </li>
        <li class="my-5">
          <span class="mr-3">👎</span> duża ilość części (konieczność trzymania
          pieniędzy np. na 6 oddzielnych kontach )
        </li>
        <li class="my-5"><span class="mr-3">👎</span> duża ilość części</li>
      </ul>
    </div>
    <div class="my-12">
      <button
        class="text-purple-50 bg-purple-600 hover:bg-purple-700 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-full text-md px-5 py-2.5 text-center mx-10 my-1"
        @click="showModal = true; scroll_to_form()"
        type="button"
        hx-get="{% url 'accounts:change_saving_method' %}"
        hx-target="#dialog"
      >
        Wybierz swoją metodę<span class="ml-3">👉</span>
      </button>
    </div>
  </div>
{% endblock %}

{% block js %}
  <script>
    function scroll_to_form() {
      var body = document.body,
        html = document.documentElement;
      var height = Math.max(
        body.scrollHeight,
        body.offsetHeight,
        html.clientHeight,
        html.scrollHeight,
        html.offsetHeight
      );
      console.log(height);
      $('html, body').animate(
        {
          scrollTop: height / 2 - window.innerHeight / 2
        },
        200
      );
    }
  </script>
{% endblock %}

templates/accounts/login.html
{% extends 'register_base.html' %}
{% load static %}
    {% block title %}
    <div>
        <h3 class="font-bold text-3xl text-gray-700">Zaloguj się</h3>
    </div>
    {% endblock %}
    {% block content %}
        <form class="flex flex-col" action="" method="POST">
        {% csrf_token %}
        <div class="mb-6 pt-3 rounded bg-gray-200">
            <input
            class="login-input"
            placeholder="Adres email"
            required
            type="text"
            name="username"
            id="username"
            maxlength="255"
            />
        </div>
        <div class="mb-6 pt-3 rounded bg-gray-200">
            <input
            class="login-input"
            placeholder="Hasło"
            required
            type="password"
            name="password"
            id="password"
            />
        </div>
        <div class="mb-6">
            <input
            type="checkbox"
            class="w-4 h-4 text-gray-600 bg-gray-100 accent-gray-400 rounded border-gray-300 focus:ring-gray-500"
            id="customCheck"
            name="remember_me"
            />
            <label
            class="ml-2 text-md font-medium text-gray-700"
            for="customCheck"
            >Zapamiętaj mnie</label
            >
        </div>
        <div class="flex justify-end">
            <a
            class="text-sm text-gray-700 hover:text-gray-700 hover:underline mb-6"
            href="{% url 'accounts:password_reset' %}"
            >Nie pamiętasz hasła?</a
            >
        </div>
        <div class="flex justify-end">
            <a
            class="text-sm text-gray-700 hover:text-gray-700 hover:underline mb-6"
            href="{% url 'accounts:register' %}"
            >Nie masz konta? Zarejestruj się</a
            >
        </div>
        <button
            type="submit"
            class="bg-purple-600 hover:bg-purple-700 text-purple-50 font-bold py-2 rounded-full shadow-lg hover:shadow-xl transition duration-200"
        >
            Zaloguj się
        </button>
        </form>
    {% endblock %}

templates/accounts/password_reset.html
{% extends 'register_base.html' %}

{% block content %}
  <div class="mb-5">
    <h3 class="text-center font-bold text-3xl text-gray-700">
      Zresetuj hasło
    </h3>
  </div>
  {% if messages %}
  <div class="mb-2">
    {% for message in messages %}
    <div
      class="flex{% if message.tags == 'warning' %} bg-red-200{% elif message.tags == 'success' %} bg-green-200 {% endif %} rounded-lg"
    >
      <p
        class="mx-auto px-2 py-2 text-xl{% if message.tags == 'warning' %} text-red-600{% elif message.tags == 'success' %} text-green-600 {% endif %}"
      >
        {{ message }}
      </p>
    </div>
    {% endfor %}
  </div>
  {% endif %}
  <div class="mt-10">
    <form class="flex flex-col" action="" method="POST">
      {% csrf_token %}
      <div class="mb-6 pt-3 rounded bg-gray-200">
        <input
          class="login-input"
          placeholder="Adres email"
          type="email"
          autocomplete="email"
          name="email"
          id="id_email"
          maxlength="255"
        />
      </div>
      <button
        type="submit"
        class="bg-purple-600 hover:bg-purple-700 text-purple-50 font-bold py-2 rounded-full shadow-lg hover:shadow-xl transition duration-200"
      >
        Zresetuj swoje hasło
      </button>
    </form>
  </div>
{% endblock %}

templates/accounts/password_reset_complete.html
{% extends 'register_base.html' %}

{% block content %}
  <div class="mb-5">
    <h3 class="text-center font-bold text-3xl text-gray-700">
      Hasło zostało zmienione
    </h3>
  </div>
  <div class="mb-2">
    <div class="flex bg-blue-200 rounded-lg">
      <p class="mx-auto px-2 py-2 text-lg text-blue-600">
        Twoje hasło zostało zmienione. Możesz się teraz zalogować za
        pomocą nowego hasła.
      </p>
    </div>
  </div>
  <a class="text-blue-600 underline" href="{% url 'accounts:login' %}"
    >Zaloguj się</a
  >
{% endblock %}

templates/accounts/password_reset_done.html
{% extends 'register_base.html' %}

{% block content %}
  <div class="mb-5">
    <h3 class="text-center font-bold text-3xl text-gray-700">
      Wysłano email
    </h3>
  </div>
  <div class="mb-2">
    <div class="flex bg-blue-200 rounded-lg">
      <p class="mx-auto px-2 py-2 text-lg text-blue-600">
        Wysłano email z instrukcjami do zresetowania hasła.
      </p>
    </div>
  </div>
{% endblock %}

templates/accounts/password_reset_email.html
{% load i18n %}
{% autoescape off %}
Otrzymałeś/aś tę wiadomość e-mail, ponieważ poprosiłeś/aś o zresetowanie hasła do konta użytkownika na platformie Monify-App.

Kliknij w poniższy link, aby przejść do widoku zmiany hasła.
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
Twoja nazwa użytkownika: {{ user.get_username }}

Jeśli to nie Ty resetowałeś hasło, zignoruj tą wiadomość.

Pozdrawiamy,
Zespół Monify-App

{% endautoescape %}

templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <div
    class="flex flex-col mx-1 space-y-5 mt-5"
    hx-trigger="load, profileDataChanged from:body"
    hx-get="{% url 'accounts:get_profile_data' %}"
    hx-target="this"
    id="loadthis"
  ></div>

  <div class="flex my-6">
    <button
      hx-get="{% url 'accounts:delete_all_data' %}"
      hx-target="#dialog1"
      @click="showConfirmationModal = true"
      class="mx-auto px-4 bg-red-500 p-2 rounded-lg text-white hover:bg-red-400"
    >
      Usuń wszystkie dane
    </button>
  </div>
</div>
{% endblock %}