Monify/urls.py
from django.conf.urls import handler404
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('finances/', include('finances.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('change_currency/', views.change_currency, name='change_currency'),
    path('change_saving_method/', views.change_saving_method, name='change_saving_method'),
    path('profile/', views.profile, name='profile_info'),
    path('info/', views.info, name='info'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('delete_all_data/', views.delete_all_data, name='delete_all_data'),
    path('get_profile_data/', views.get_profile_data, name='get_profile_data'),
    path('password_reset/',
        auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html',
        email_template_name = 'accounts/password_reset_email.html',
        subject_template_name='accounts/password_reset_subject.txt',
        success_url = reverse_lazy('accounts:password_reset_done')),
        name='password_reset'),
    path('password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',
        success_url = reverse_lazy('accounts:password_reset_complete')),
        name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),
]

website/urls.py
from django.urls import path

from . import views

app_name = 'website'

urlpatterns = [
    path('', views.index, name='index'),
    path('app_info/', views.app_info, name='app_info'),
    path('methods_info/', views.methods_info, name='methods_info'),
]

templates/index_base.html
{% load static %}

<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
      integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    ></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/8.2.0/swiper-bundle.css" integrity="sha512-gXVFcB8iYgOunkUICvoq9/af88msQVcPGBUk4nVEtuX7/RhCUuoZ0Ip/fGN8oehJOJj5hXc+aLIE0Nh8+yhDYw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/8.2.0/swiper-bundle.min.js"
      integrity="sha512-3B6rL2BzDOGBXW2tzEjkmiTvtU2VQrYS+Xr8nIl3oladt+4zw05FIgzx6QTqXPYLXb74jDUsT3l3gtdDNi5SVA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    ></script>
    
    <!-- favicon-16x16.png - The classic favicon, displayed in the tabs. -->
    <link rel="icon" type="image/png" href="{% static 'img/icon.png' %}" sizes="16x16">
    <!-- favicon-32x32.png - For Safari on Mac OS. -->
    <link rel="icon" type="image/png" href="{% static 'img/icon32.png' %}" sizes="32x32">
    <title>Monify-App - kontroluj mądrze swoje wydatki</title>
  </head>
  <body  x-data="{openMobileMenu: false}">
    <!-- Navbar -->
    {% url 'website:index' as index %}
    {% url 'website:app_info' as app_info %}
    <nav class="px-6 py-2 shadow-xl sticky top-0 bg-white">
      <div class="flex items-center justify-between">
        <!-- Logo -->
        <div class="pt-1">
          <a href="{{ index }}">
            <img src="{% static 'img/purplelogo-mini.png' %}" class="ml-6 w-12 h-12" alt="Mini purple logo Monify-App" />
          </a>
        </div>
        <!-- Button -->
        <div>
          <button class="md:hidden" @click="openMobileMenu = !openMobileMenu">
            <i class="fa-solid fa-bars block text-xl font-bold" :class="{'fa-bars': openMobileMenu === false, 'fa-xmark': openMobileMenu === true}"></i>
          </button>
        </div>
        <div class="hidden md:flex space-x-6 mx-5 text-gray-400">
          <a href="{{ index }}" class="hover:text-gray-600 hover:underline hover:underline-offset-8 my-auto{% if page_path == index %} text-gray-600 underline underline-offset-8{% endif %}">Strona główna</a>
          <a href="{{ app_info }}" class="hover:text-gray-600 hover:underline hover:underline-offset-8 my-auto{% if page_path == app_info %} text-gray-600 underline underline-offset-8{% endif %}">Jak działa</a>
          <a
            href="{% url 'accounts:login' %}"
            class="hidden md:block p-3 px-6 pt-2 text-white bg-purple-400 rounded-full hover:bg-purple-500 baseline text-sm"
          >Zaloguj się</a>
        </div>
      </div>

      <!-- Mobile Menu -->
      <div class="md:hidden" x-show="openMobileMenu">
        <div class="absolute flex flex-col items-center self-end py-8 mt-0 space-y-6 font-bold bg-white sm:w-full left-0 right-0 drop-shadow-md text-gray-600">
          <a href="{{ index }}" class="hover:text-gray-400 my-auto">Strona główna</a>
          <a href="{{ app_info }}" class="hover:text-gray-400 my-auto">Jak działa</a>
          <a
            href="{% url 'accounts:login' %}"
            class="p-3 px-6 pt-2 text-white bg-purple-400 rounded-full hover:bg-purple-500 baseline text-sm"
          >Zaloguj się</a>
        </div>
      </div>
    </nav>
    {% block content %}
    {% endblock %}
    
    <footer class="bg-purple-400 flex items-center justify-between p-5">
      <span class="text-sm text-white text-center mx-auto"
      >Copyright © {% if today_year == 2022 %}2022 {% else %}2022-{{ today_year }} {% endif %} <a href="" class="hover:underline">Monify-App</a>. All Rights
        Reserved.
      </span>
    </footer>
      {% block js %}
      {% endblock %}
      <script
      src="https://cdnjs.cloudflare.com/ajax/libs/alpinejs/3.10.0/cdn.js"
      integrity="sha512-he/Dr0VcSDmO6nVoy73f3clLnvpyqWmhju0ZuzbTIqUhMs3QIhbY7fL2GIVQJntQbXZz++NrXXJgLeaq62awIg=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    ></script>
  </body>
</html>

templates/password_reset_base.html
{% load static %}

<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <!-- favicon-16x16.png - The classic favicon, displayed in the tabs. -->
    <link
      rel="icon"
      type="image/png"
      href="{% static 'img/icon.png' %}"
      sizes="16x16"
    />
    <!-- favicon-32x32.png - For Safari on Mac OS. -->
    <link
      rel="icon"
      type="image/png"
      href="{% static 'img/icon32.png' %}"
      sizes="32x32"
    />
    <title>Monify-App - kontroluj mądrze swoje wydatki</title>
  </head>
  <body class="bg-purple-600 min-h-screen pt-5 pb-5 px-2 md:px-0">
    <div>
        <a href="{% url 'website:index' %}" class="text-xl ml-5 text-white"
          ><i class="fa-solid fa-circle-chevron-left"></i>
          <span class="hidden md:inline-block">Powrót</span></a
        >
    </div>
    <div class="mx-auto">
      <a href="{% url 'website:index' %}">
        <img
          src="{% static 'img/whitelogo.png' %}"
          class="mx-auto w-32 h-28"
          alt="White logo Monify-App"
        />
      </a>
    </div>
    <main
      class="bg-white max-w-lg mx-auto p-8 md:p-12 my-8 rounded-lg shadow-2xl"
    >
      <section>
        {% block content %}
        {% endblock %}
      </section>
    </main>
  </body>
</html>

templates/register_base.html
{% load static %}

<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <!-- favicon-16x16.png - The classic favicon, displayed in the tabs. -->
    <link
      rel="icon"
      type="image/png"
      href="{% static 'img/icon.png' %}"
      sizes="16x16"
    />
    <!-- favicon-32x32.png - For Safari on Mac OS. -->
    <link
      rel="icon"
      type="image/png"
      href="{% static 'img/icon32.png' %}"
      sizes="32x32"
    />
    <title>Monify-App - kontroluj mądrze swoje wydatki</title>
  </head>
  <body class="bg-purple-600 min-h-screen pt-5 pb-5 px-2 md:px-0">
    <div>
      <a href="{% url 'website:index' %}" class="text-xl ml-5 text-white"
        ><i class="fa-solid fa-circle-chevron-left"></i>
        <span class="hidden md:inline-block">Powrót</span></a
      >
    </div>
    <div class="mx-auto">
      <img
        src="{% static 'img/whitelogo.png' %}"
        class="mx-auto w-32 h-28"
        alt="White logo Monify-App"
      />
    </div>
    <main
      class="bg-white max-w-lg mx-auto p-8 md:p-12 my-8 rounded-lg shadow-2xl"
    >
      <section class="">
        {% block title %}
        {% endblock %}
        {% if messages %}
        <div class="mb-2">
          {% for message in messages %}
          <div
            class="mt-3 flex{% if message.tags == 'warning' %} bg-red-200{% elif message.tags == 'success' %} bg-green-200 {% endif %} rounded-lg"
          >
            <p
              class="mx-auto px-2 py-2 text-xl{% if message.tags == 'warning' %} text-red-600{% elif message.tags == 'success' %} text-green-600 {% endif %}"
            >
              {{ message }}
            </p>
          </div>
          {% endfor %}
        </div>
        {% endif %}
        <div class="mt-10">
            {% block content %}
            {% endblock %}
        </div>
      </section>
    </main>
    {% block js %}
    {% endblock %}
  </body>
</html>