Monify/urls.py
from django.conf.urls import handler404
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('finances/', include('finances.urls')),
    path('accounts/', include('accounts.urls')),
]

finances/urls.py
from django.urls import path, re_path

from finances import views

app_name = 'finances'

urlpatterns = [
    path('balance_list_get/', views.BalanceListView.as_view(), name='balance_list_get'),
    path('balances/', views.balance_list, name='balances'),
    path('balance_create/', views.BalanceCreateView.as_view(), name='balance_create'),
    path('balance_update/<int:pk>', views.BalanceUpdateView.as_view(), name='balance_update'),
    re_path(r'^balance_delete/(?P<part_id>[0-9]+)/$', views.delete_balance, name='balance_delete'),

    path('outcome_list_get/', views.OutcomeListView.as_view(), name='outcome_list_get'),
    path('outcomes/', views.outcome_list, name='outcomes'),
    path('outcome_create/', views.OutcomeCreateView.as_view(), name='outcome_create'),
    path('outcome_update/<int:pk>', views.OutcomeUpdateView.as_view(), name='outcome_update'),
    re_path(r'^outcome_delete/(?P<part_id>[0-9]+)/$', views.delete_outcome, name='outcome_delete'),

    path('income_list_get/', views.IncomeListView.as_view(), name='income_list_get'),
    path('incomes/', views.income_list, name='incomes'),
    path('income_create/', views.IncomeCreateView.as_view(), name='income_create'),
    path('income_update/<int:pk>', views.IncomeUpdateView.as_view(), name='income_update'),
    re_path(r'^income_delete/(?P<part_id>[0-9]+)/$', views.delete_income, name='income_delete'),

    path('get_summary_data/', views.get_summary_data, name='get_summary_data'),
    path('get_statistics_data/', views.get_statistics_data, name='get_statistics_data'),
    path('get_progress_data/', views.get_progress_data, name='get_progress_data'),
    path('get_incomes_vs_outcomes_chart/', views.get_incomes_vs_outcomes_chart, name='get_incomes_vs_outcomes_chart'),
    path('get_income_or_outcome_by_type/', views.get_income_or_outcome_by_type, name='get_income_or_outcome_by_type'),
    path('get_income_or_outcome_bar_chart/', views.get_income_or_outcome_bar_chart, name='get_income_or_outcome_bar_chart'),

    path('raport_form', views.raport_form, name='raport_form'),
    path('generate_CSV', views.generate_CSV, name='generate_CSV'),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('savings/', views.savings, name='savings'),
    path('progress/', views.progress, name='progress'),
    path('stats/', views.stats, name='stats'),
]

finances/models.py
from django.db import models
from django.contrib.auth.models import User

# Balance model
class Balance(models.Model):
    
    class BTypes(models.IntegerChoices):
        STA = 1, "Standardowe"
        OSZ = 2, "Oszczędnościowe"
        
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='balances')
    name = models.CharField(max_length=60)
    value = models.DecimalField(max_digits=10, decimal_places=2)
    type = models.PositiveSmallIntegerField(choices=BTypes.choices)
    date = models.DateField()
    comment = models.TextField(null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} - {self.value}"

    class Meta:
        verbose_name_plural = 'balances'
        ordering = ['-date']
        
# Outcome model
class Outcome(models.Model):
    class OTypes(models.IntegerChoices):
        OPM = 1, "Opłata za mieszkanie"
        SPK = 2, "Spłata kredytów"
        RAC = 3, "Rachunki"
        HIG = 4, "Higiena"
        LEK = 5, "Koszty leczenia i leki"
        KOS = 6, "Kosmetyki"
        SZP = 7, "Wydatki na szkołe i przedszkole"
        JED = 8, "Jedzenie i picie"
        TRA = 9, "Transport"
        UBE = 10, "Ubezpieczenie"
        SAM = 11, "Samochód"
        PAR = 12, "Parking i opłaty"
        ZWI = 13, "Karma dla zwierząt"
        DUZ = 14, "Duże zakupy"
        REM = 15, "Remont"
        SPR = 16, "Wymiana sprzętów domowych"
        WAK = 17, "Wakacje"
        NIW = 18, "Niespodziewane wydatki(np. naprawa samochodu)"
        MAN = 19, "Mandat"
        KAR = 20, "Kary"
        RES = 21, "Restauracje"
        PUB = 22, "Puby i bary"
        KLU = 23, "Kluby"
        FIL = 24, "Filmy"
        GRY = 25, "Gry"
        MUZ = 26, "Muzyka"
        SUB = 27, "Subskrypcje"
        ELE = 28, "Elektronika"
        KIN = 29, "Kino i teatr"
        WYJ = 30, "Wyjście ze znajomymi"
        ZAB = 31, "Zabawa"
        KON = 32, "Koncert"
        ROZ = 33, "Rozrywka"
        DEK = 34, "Dekoracje"
        MEB = 35, "Meble"
        ATR = 36, "Atrakcje/wypoczynek"
        ZAK = 37, "Zakupy"
        KSI = 38, "Książki"
        KUR = 39, "Kursy"
        SZK = 40, "Szkolenia"
        MEN = 41, "Mentoring"
        AKC = 42, "Akcje"
        KRY = 43, "Kryptowaluty"
        NIE = 44, "Nieruchomości"
        DOP = 45, "Dochód pasywny"
        FUN = 46, "Fundusze"
        OSZ = 47, "Oszczędności"
        WPL = 48, "Wpłata na lokate"
        SUR = 49, "Surowce"
        WAL = 50, "Waluty"
        OBL = 51, "Obligacje"
        DAT = 52, "Datki na fundacje"
        POM = 53, "Pomoc potrzebującym"
        PRE = 54, "Prezenty"
        
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='outcomes')
    value = models.DecimalField(max_digits=10, decimal_places=2)
    type = models.PositiveSmallIntegerField(choices=OTypes.choices)
    balance = models.ForeignKey(Balance, on_delete=models.CASCADE)
    date = models.DateField()
    comment = models.TextField(null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.type} - {self.value}"

    class Meta:
        verbose_name_plural = 'outcomes'
        ordering = ['-date', '-created_at']
        constraints = [
            models.CheckConstraint(check=models.Q(value__gte='0'), name='outcome_value_non_negative'),
        ]

# Income model
class Income(models.Model):
    class ITypes(models.IntegerChoices):
        PRE = 1, "Prezent"
        PEN = 2, "Pensja"
        BON = 3, "Bonus"
        NAG = 4, "Nagroda"
        ZWR = 5, "Zwrot"
        OSZ = 6, "Oszczędności"
        INN = 7, "Inne"
        
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='incomes')
    value = models.DecimalField(max_digits=10, decimal_places=2)
    type = models.PositiveSmallIntegerField(choices=ITypes.choices)
    balance = models.ForeignKey(Balance, on_delete=models.CASCADE)
    date = models.DateField()
    comment = models.TextField(null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.type} - {self.value}"

    class Meta:
        verbose_name_plural = 'incomes'
        ordering = ['-date', '-created_at']
        constraints = [
            models.CheckConstraint(check=models.Q(value__gte='0'), name='income_value_non_negative'),
        ]

finances/views.py
import calendar
import csv
import json
import locale
from decimal import Decimal
from dateutil import relativedelta
from datetime import date, timedelta, datetime
from django.utils.formats import date_format
from django.utils import translation
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum, Q
from django.db.models.functions import ExtractYear
from django.http import HttpResponse, JsonResponse
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

from .forms import BalanceForm, OutcomeForm, IncomeForm
from .models import Balance, Outcome, Income
from accounts.models import Account

# Balance Views

# Balance List View
class BalanceListView(LoginRequiredMixin, ListView):
    login_url = 'accounts:login'
    model = Balance
    paginate_by = 10
    template_name = 'finances/objects_table.html'

    def get_queryset(self):
        user = self.request.user
        return Balance.objects.filter(user=user)

    def get_context_data(self,**kwargs):
        user = self.request.user
        context = super(BalanceListView,self).get_context_data(**kwargs)
        if Balance.objects.filter(user=user).exists():
            context['data_exist'] = True
        context['list_what'] = 'Balance'
        return context

# Balance Create View
class BalanceCreateView(LoginRequiredMixin, CreateView):
    login_url = 'accounts:login'
    model = Balance
    form_class = BalanceForm
    template_name = 'finances/balance_income_outcome_form.html'
    extra_context = {'header': 'Dodaj konto'}

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponse(
                status=204,
                headers={
                    'HX-Trigger': json.dumps({
                        "objectListChanged": None
                    })
                })

# Balance Update View
class BalanceUpdateView(LoginRequiredMixin, UpdateView):
    login_url = 'accounts:login'
    model = Balance
    form_class = BalanceForm
    template_name = 'finances/balance_income_outcome_form.html'
    extra_context = {'header': 'Edytuj konto'}

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponse(
                status=204,
                headers={
                    'HX-Trigger': json.dumps({
                        "objectListChanged": None
                    })
                })

@login_required(login_url='accounts:login')
def balance_list(request):
    return render(request, 'finances/balances.html')

# Balance delete
@login_required(login_url='accounts:login')
def delete_balance(request, part_id=None):
    balance = Balance.objects.filter(id=part_id)
    if request.method == "POST":
        balance.delete()
        return HttpResponse(
                    status=204,
                    headers={
                        'HX-Trigger': json.dumps({
                            "objectListChanged": None,
                        })
                    })
    return render(request, 'finances/balance_income_outcome_confirm_delete.html', context={'model':'konto', 'model_name':balance[0].name})

# Outcome Views

# Outcome List View
class OutcomeListView(LoginRequiredMixin, ListView):
    login_url = 'accounts:login'
    model = Outcome
    paginate_by = 10
    template_name = 'finances/objects_table.html'

    def get_queryset(self):
        user = self.request.user
        return Outcome.objects.filter(user=user)

    def get_context_data(self,**kwargs):
        user = self.request.user
        context = super(OutcomeListView,self).get_context_data(**kwargs)
        if Outcome.objects.filter(user=user).exists():
            context['data_exist'] = True
        context['list_what'] = 'Outcome'
        return context

# Outcome Create View
class OutcomeCreateView(LoginRequiredMixin, CreateView):
    login_url = 'accounts:login'
    model = Outcome
    form_class = OutcomeForm
    template_name = 'finances/balance_income_outcome_form.html'
    extra_context = {'header': 'Dodaj wydatek'}

    def get_form_class(self):
        modelform = super().get_form_class()
        modelform.base_fields['balance'].limit_choices_to = {'user': self.request.user, 'type': 1}
        return modelform

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        balance = Balance.objects.filter(id=self.object.balance.id)
        balance_value = balance.aggregate(total=Sum('value'))['total']
        balance_value -= self.object.value
        balance.update(value = balance_value)
        return HttpResponse(
                status=204,
                headers={
                    'HX-Trigger': json.dumps({
                        "objectListChanged": None
                    })
                })

# Outcome Update View
class OutcomeUpdateView(LoginRequiredMixin, UpdateView):
    login_url = 'accounts:login'
    model = Outcome
    form_class = OutcomeForm
    template_name = 'finances/balance_income_outcome_form.html'
    extra_context = {'header': 'Edytuj wydatek'}

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        old_outcome_value = Outcome.objects.filter(id=self.object.id).aggregate(total=Sum('value'))['total']
        old_outcome_balance = Outcome.objects.filter(id=self.object.id).values('balance_id')[0]['balance_id']
        self.object.save()
        balance = Balance.objects.filter(id=self.object.balance.id)
        balance_value = balance.aggregate(total=Sum('value'))['total']
        value_to_substract = self.object.value - old_outcome_value

        if old_outcome_balance != self.object.balance.id:
            old_balance = Balance.objects.filter(id = old_outcome_balance)
            old_balance_value = old_balance.aggregate(total=Sum('value'))['total']
            old_balance_value += old_outcome_value
            old_balance.update(value = old_balance_value)
            value_to_substract = self.object.value

        balance_value -= value_to_substract
        balance.update(value = balance_value)
        return HttpResponse(
                status=204,
                headers={
                    'HX-Trigger': json.dumps({
                        "objectListChanged": None
                    })
                })

# Outcome delete
@login_required(login_url='accounts:login')
def delete_outcome(request, part_id=None):
    outcome = Outcome.objects.filter(id=part_id)
    outcome1 = outcome.get()
    outcome_value = outcome.aggregate(total=Sum('value'))['total']
    balance = Balance.objects.filter(id=outcome1.balance.id)
    balance_value = balance.aggregate(total=Sum('value'))['total']

    if request.method == "POST":
        outcome.delete()
        balance_value += outcome_value
        balance.update(value = balance_value)
        return HttpResponse(
                    status=204,
                    headers={
                        'HX-Trigger': json.dumps({
                            "objectListChanged": None,
                        })
                    })
    return render(request, 'finances/balance_income_outcome_confirm_delete.html', context={'model': 'wydatek','model_name':outcome[0].get_type_display, 'model_value':outcome[0].value, 'model_date': outcome[0].date})

@login_required(login_url='accounts:login')
def outcome_list(request):
    return render(request, 'finances/incomes_outcomes.html', context={'list_what': 'Wydatki'})

# Income Views

# Income List View
class IncomeListView(LoginRequiredMixin, ListView):
    login_url = 'accounts:login'
    model = Income
    paginate_by = 10
    template_name = 'finances/objects_table.html'

    def get_queryset(self):
        user = self.request.user
        return Income.objects.filter(user=user)

    def get_context_data(self,**kwargs):
        user = self.request.user
        context = super(IncomeListView,self).get_context_data(**kwargs)
        if Income.objects.filter(user=user).exists():
            context['data_exist'] = True
        context['list_what'] = 'Income'
        return context

# Income Create View
class IncomeCreateView(LoginRequiredMixin, CreateView):
    login_url = 'accounts:login'
    model = Income
    form_class = IncomeForm
    template_name = 'finances/balance_income_outcome_form.html'
    extra_context = {'header': 'Dodaj przychód'}

    def get_form_class(self):
        modelform = super().get_form_class()
        modelform.base_fields['balance'].limit_choices_to = {'user': self.request.user, 'type': 1}
        return modelform

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        balance = Balance.objects.filter(id=self.object.balance.id)
        balance_value = balance.aggregate(total=Sum('value'))['total']
        balance_value += self.object.value
        balance.update(value = balance_value)
        return HttpResponse(
                status=204,
                headers={
                    'HX-Trigger': json.dumps({
                        "objectListChanged": None,
                    })
                })

# Income Update View
class IncomeUpdateView(LoginRequiredMixin, UpdateView):
    login_url = 'accounts:login'
    model = Income
    form_class = IncomeForm
    template_name = 'finances/balance_income_outcome_form.html'
    extra_context = {'header': 'Edytuj przychód'}
    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user

templates/finances/incomes_outcomes.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div x-init="openDropdownTransactions = true">
  <!-- Title -->
  <h1 class="ml-10 my-8 text-3xl font-bold">{{ list_what }}</h1>

  <div class="flex flex-row md:ml-10 mx-5">
    {% if list_what == "Wydatki" %}
    <button
      class="mx-5 shadow-md border-2 border-purple-600 rounded-lg px-3 py-2 text-gray-600 hover:text-gray-800 hover:border-purple-800"
      @click="showModal = true"
      type="button"
      hx-get="{% url 'finances:outcome_create' %}"
      hx-target="#dialog"
    >
      <i class="fa-solid fa-plus"></i> Dodaj wydatek
    </button>
    <button
      class="mx-5 shadow-md border-2 border-purple-600 rounded-lg px-3 py-2 text-gray-600 hover:text-gray-800 hover:border-purple-800"
      @click="showModal = true"
      type="button"
      hx-get="{% url 'finances:raport_form' %}?raport_object=outcomes"
      hx-target="#dialog"
    >
      <i class="fa-solid fa-download"></i> Generuj raport
    </button>
    {% elif list_what == "Przychody" %}
    <button
      class="mx-5 shadow-md border-2 border-purple-600 rounded-lg px-3 py-2 text-gray-600 hover:text-gray-800 hover:border-purple-800"
      @click="showModal = true"
      type="button"
      hx-get="{% url 'finances:income_create' %}"
      hx-target="#dialog"
    >
      <i class="fa-solid fa-plus"></i> Dodaj przychód
    </button>
    <button
      class="mx-5 shadow-md border-2 border-purple-600 rounded-lg px-3 py-2 text-gray-600 hover:text-gray-800 hover:border-purple-800"
      @click="showModal = true"
      type="button"
      hx-get="{% url 'finances:raport_form' %}?raport_object=incomes"
      hx-target="#dialog"
    >
      <i class="fa-solid fa-download"></i> Generuj raport
    </button>
    {% endif %}
  </div>

  <div class="relative md:w-10/12 mx-10 my-10 overflow-x-auto sm:rounded-lg">
    <div hx-trigger="load, objectListChanged from:body" 
        {% if list_what == "Wydatki" %} 
            hx-get="{% url 'finances:outcome_list_get' %}" 
        {% elif list_what == "Przychody" %} 
            hx-get="{% url 'finances:income_list_get' %}" 
        {% endif %} 
        hx-target="this" 
        id="loadthis"
    >
    </div>
</div>
</div>
{% endblock %} 

{% block js %}
<script>
  function scroll_to_form() {
    var body = document.body,
      html = document.documentElement;
    var height = Math.max(
      body.scrollHeight,
      body.offsetHeight,
      html.clientHeight,
      html.scrollHeight,
      html.offsetHeight
    );
    console.log(height);
    $('html, body').animate(
      {
        scrollTop: height / 2 - window.innerHeight / 2
      },
      200
    );
  }
</script>
{% endblock %}

templates/finances/outcome_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    

    <!-- Table-->
    

<div x-init="openDropdownTransactions = true">

    <h1 class="ml-10 my-8 text-3xl">{{ list_what }}</h1>

    <div class="flex flex-row md:ml-10 mx-5">
        {% if list_what == "Wydatki" %}
        <button class="mx-5 shadow-md border-2 border-purple-600 rounded-lg px-3 py-2 text-gray-600 hover:text-gray-800 hover:border-purple-800" @click="showModal = true" type="button" hx-get="{% url 'finances:outcome_create' %}" hx-target="#dialog"><i class="fa-solid fa-plus"></i> Dodaj wydatek</button>
        <button class="mx-5 shadow-md border-2 border-purple-600 rounded-lg px-3 py-2 text-gray-600 hover:text-gray-800 hover:border-purple-800" @click="showModal = true" type="button" hx-get="{% url 'finances:raport_form' %}?raport_object=outcomes" hx-target="#dialog"><i class="fa-solid fa-download"></i> Generuj raport</button>
        {% elif list_what == "Przychody" %}
        <button class="mx-5 shadow-md border-2 border-purple-600 rounded-lg px-3 py-2 text-gray-600 hover:text-gray-800 hover:border-purple-800" @click="showModal = true" type="button" hx-get="{% url 'finances:income_create' %}" hx-target="#dialog"><i class="fa-solid fa-plus"></i> Dodaj przychód</button>
        <button class="mx-5 shadow-md border-2 border-purple-600 rounded-lg px-3 py-2 text-gray-600 hover:text-gray-800 hover:border-purple-800" @click="showModal = true" type="button" hx-get="{% url 'finances:raport_form' %}?raport_object=incomes" hx-target="#dialog"><i class="fa-solid fa-download"></i> Generuj raport</button>
        {% endif %}
    </div>

    <!-- <table id="list-table" class="ml-10 my-6 table-auto gap-10">
         <thead>
        <tr>
        </tr>
        </thead> 
        <tbody hx-get="{% url 'finances:balance_list_get' %}" hx-trigger="load" id="table-body" class="">
            <tr><td>Ładuje dane...</td></tr>
        </tbody>
    </table> -->

    <div class="relative md:w-10/12 mx-10 my-10 overflow-x-auto sm:rounded-lg">
        <div hx-trigger="load, movieListChanged from:body"
            {% if list_what == "Wydatki" %}
            hx-get="{% url 'finances:outcome_list_get' %}"
            {% elif list_what == "Przychody" %}
            hx-get="{% url 'finances:income_list_get' %}"
            {% endif %}
            hx-target="this" id="loadthis"></div>
        <!-- <table class="w-full text-sm text-left text-gray-500"> -->
            <!-- <thead class="text-xs text-gray-700 uppercase bg-gray-50">
                <tr>
                    <th scope="col" class="px-6 py-3">
                        Product name
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Color
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Category
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Price
                    </th>
                    <th scope="col" class="px-6 py-3">
                        <span class="sr-only">Edit</span>
                    </th>
                </tr>
            </thead> -->
            <!-- <tbody  id="table-body"> -->
                <!-- <tr class="border-b  odd:bg-white even:bg-gray-300 ">
                    <th scope="row" class="px-6 py-4 font-medium text-gray-900">
                        Apple MacBook Pro 17"
                    </th>
                    <td class="px-6 py-4">
                        Sliver
                    </td>
                    <td class="px-6 py-4">
                        Laptop
                    </td>
                    <td class="px-6 py-4">
                        $2999
                    </td>
                    <td class="px-6 py-4 text-right">
                        <a href="#" class="font-medium text-blue-600 hover:underline">Edit</a>
                    </td>
                </tr>
                <tr class="border-b  odd:bg-white even:bg-gray-300">
                    <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                        Microsoft Surface Pro
                    </th>
                    <td class="px-6 py-4">
                        White
                    </td>
                    <td class="px-6 py-4">
                        Laptop PC
                    </td>
                    <td class="px-6 py-4">
                        $1999
                    </td>
                    <td class="px-6 py-4 text-right">
                        <a href="#" class="font-medium text-blue-600 hover:underline">Edit</a>
                    </td>
                </tr>
                <tr class="border-b odd:bg-white even:bg-gray-300">
                    <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                        Magic Mouse 2
                    </th>
                    <td class="px-6 py-4">
                        Black
                    </td>
                    <td class="px-6 py-4">
                        Accessories
                    </td>
                    <td class="px-6 py-4">
                        $99
                    </td>
                    <td class="px-6 py-4 text-right">
                        <a href="#" class="font-medium text-blue-600 hover:underline">Edit</a>
                    </td>
                </tr>
                <tr class="border-b  odd:bg-white even:bg-gray-300">
                    <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                        Google Pixel Phone
                    </th>
                    <td class="px-6 py-4">
                        Gray
                    </td>
                    <td class="px-6 py-4">
                        Phone
                    </td>
                    <td class="px-6 py-4">
                        $799
                    </td>
                    <td class="px-6 py-4 text-right">
                        <a href="#" class="font-medium text-blue-600 hover:underline">Edit</a>
                    </td>
                </tr>
                <tr class="odd:bg-white even:bg-gray-300">
                    <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                        Apple Watch 5
                    </th>
                    <td class="px-6 py-4">
                        Red
                    </td>
                    <td class="px-6 py-4">
                        Wearables
                    </td>
                    <td class="px-6 py-4">
                        $999
                    </td>
                    <td class="px-6 py-4 text-right">
                        <a href="#" class="font-medium text-blue-600 hover:underline">Edit</a>
                    </td>
                </tr> -->
            <!-- </tbody> -->
        <!-- </table> -->
    </div>
    <!-- {% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %} -->
</div>




{% endblock %}
<script src="{% static 'js/dialog.js' %}"></script>
<script>
    function scroll_to_form() {
    var body = document.body,
        html = document.documentElement;
		var height = Math.max( body.scrollHeight, body.offsetHeight, 
                       html.clientHeight, html.scrollHeight, html.offsetHeight );
    console.log(height);
    $('html, body').animate({
        scrollTop: height/2 - window.innerHeight/2
    }, 200);
}
</script>
{% block js %}

    
{% endblock %}